// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScreenshotMonitor.Data.Context;

#nullable disable

namespace ScreenshotMonitor.Data.Migrations
{
    [DbContext(typeof(SmDbContext))]
    [Migration("20260830191207_AddBackupRetentionPolicy")]
    partial class AddBackupRetentionPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.AdminAuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.AttendanceIdlePeriod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AttendanceRecordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceRecordId");

                    b.ToTable("AttendanceIdlePeriods");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.AttendanceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ClockInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClockOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TotalIdleDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "DeviceId", "OriginalPath")
                        .IsUnique();

                    b.ToTable("BackupFiles");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupInventoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BackedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long?>("ModifiedUnixSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("RequiresBackup")
                        .HasColumnType("boolean");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Path")
                        .IsUnique();

                    b.ToTable("BackupInventoryItems");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupInventoryRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BackupCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InventoryCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("BackupInventoryRuns");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupPathRule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Path")
                        .IsUnique();

                    b.ToTable("BackupPathRules");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupRestoreRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("FileVersionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FileVersionId");

                    b.HasIndex("EmployeeId", "DeviceId", "Status");

                    b.ToTable("BackupRestoreRequests");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.DeviceSecurityPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("ActiveAppTrackingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("AttendanceRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("FileChangeAuditEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IdleTrackingEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("MaxBackupBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxVersionsPerFile")
                        .HasColumnType("integer");

                    b.Property<bool>("MonitoringEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("NetworkAuditEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("RestoreEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<bool>("RetentionEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ScreenshotsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByAdminId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UsbAuditEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceSecurityPolicies");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.FileVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BackupFileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("EncryptedSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("PlainSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SourceModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BackupFileId");

                    b.HasIndex("ContentHash");

                    b.ToTable("FileVersions");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AdminId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.ProjectEmployee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("ScreenshotInterval")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TotalActiveTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectEmployees");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Screenshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.SecurityEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SecurityEvents");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ActiveDuration")
                        .HasColumnType("interval");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.SessionBackgroundApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TotalUsageTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionBackgroundApps");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.SessionForegroundApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TotalUsageTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionForegroundApps");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.StorageDeletionJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.ToTable("StorageDeletionJobs");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TotalOnlineTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.AttendanceIdlePeriod", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.AttendanceRecord", "AttendanceRecord")
                        .WithMany("IdlePeriods")
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceRecord");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupFile", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupInventoryItem", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.BackupInventoryRun", "Run")
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupInventoryRun", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupRestoreRequest", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.FileVersion", "FileVersion")
                        .WithMany("RestoreRequests")
                        .HasForeignKey("FileVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileVersion");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Device", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.DeviceSecurityPolicy", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.Device", "Device")
                        .WithOne()
                        .HasForeignKey("ScreenshotMonitor.Data.Entities.DeviceSecurityPolicy", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.FileVersion", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.BackupFile", "BackupFile")
                        .WithMany("Versions")
                        .HasForeignKey("BackupFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupFile");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Project", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.ProjectEmployee", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.User", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScreenshotMonitor.Data.Entities.Project", "Project")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Screenshot", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.Session", "Session")
                        .WithMany("Screenshots")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.SecurityEvent", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Session", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.User", "Employee")
                        .WithMany("Sessions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScreenshotMonitor.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.SessionBackgroundApp", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.Session", "Session")
                        .WithMany("BackgroundApps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.SessionForegroundApp", b =>
                {
                    b.HasOne("ScreenshotMonitor.Data.Entities.Session", "Session")
                        .WithMany("ForegroundApps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.AttendanceRecord", b =>
                {
                    b.Navigation("IdlePeriods");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupFile", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.BackupInventoryRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.FileVersion", b =>
                {
                    b.Navigation("RestoreRequests");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Project", b =>
                {
                    b.Navigation("ProjectEmployees");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.Session", b =>
                {
                    b.Navigation("BackgroundApps");

                    b.Navigation("ForegroundApps");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("ScreenshotMonitor.Data.Entities.User", b =>
                {
                    b.Navigation("ProjectEmployees");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
